### ISSUE TITLE
folder of enchantments extractor

### ISSUE THREAD

**Issue by ThomasDeStrooper** [Mrredstone5230/EnchantExtractor#1]
Is there a folder for the enchantments extractor plugin that i can edit the messages etc

**Comment by SB2DD** [comment]
There currently isnt a config file, but it sure is something I could work on. I haven't been working on my plugins recently, but I can sure give it a try!

**Comment by SB2DD** [comment]
Added in v1.2. Available here on github or on spigotmc.org. Thanks for the suggestion!
